config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post '/register' => 'welcome#register'
  get '/unsubscribe' => 'welcome#unsubscribe', as: :unsubscribe
  get '/about' => 'welcome#about', as: :about
  get '/contact' => 'welcome#contact', as: :contact
  post '/contact' => 'welcome#contact_send', as: :contact_send

end

app/models/contact.rb
# Class for contact object without persistence
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
  validates_format_of :email, with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i

  def initialize(attributes = {})
    attributes.each do |name, value|
      send "#{name}=", value
    end
  end
end

app/models/movie.rb
# Movie entity
class Movie < ActiveRecord::Base
  has_many :sessions
  validates_uniqueness_of :aid
  has_attached_file :poster, styles: {
    small: '200x200>'
  }
  validates_attachment_content_type :poster, content_type: %r{\Aimage\/.*\Z}

  # Return sessions grouped by date
  # @return [Hash<Date,DateTime>]
  def sessions_by_date_for(interval)
    dates = {}
    sessions.where(date: interval).pluck(:date).each do |datetime|
      dates[datetime.to_date] ||= []
      dates[datetime.to_date] << datetime
    end
    dates
  end

  def self.current_week
    joins(:sessions).where(
      'sessions.date' => ApplicationController.helpers.current_theater_week
    ).distinct
  end

  def self.next_week
    joins(:sessions).where(
      'sessions.date' => ApplicationController.helpers.next_theater_week
    ).distinct
  end

  def allocine_link
    "http://www.allocine.fr/film/fichefilm_gen_cfilm=#{aid}.html"
  end
end

app/models/session.rb
# Theaters sessions (linked to movies)
class Session < ActiveRecord::Base
  belongs_to :movie

  validates_uniqueness_of :movie_id, scope: :date
end

app/models/user.rb
# User emails
class User < ActiveRecord::Base
  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
                    }
end

app/controllers/application_controller.rb
# Global application controller (must be extended)
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
# Main class for webapp
class WelcomeController < ApplicationController
  include TheaterWeekHelper

  def index
    @current_week = Movie.joins(:sessions).where(
      'sessions.date' => current_theater_week
    ).distinct

    @next_week = Movie.joins(:sessions).where(
      'sessions.date' => next_theater_week
    ).distinct
  end

  def register
    user = User.create(email: params[:email])
    result = user.valid? ? :success : :error

    respond_to do |format|
      format.html do
        flash[result] = t(result, scope: 'email.add')
        redirect_to :root
      end
      format.json { render json: { result => t(result, scope: 'email.add') } }
    end
  end

  def unsubscribe
    destroyed_users = User.destroy_all(email: params[:email])
    result = destroyed_users.count > 0 ? :success : :error
    flash[result] = t("email.remove.#{result}")
    redirect_to root_path
  end

  def contact
    @contact = Contact.new
  end

  def contact_send
    @contact = Contact.new(contact_params)
    result = :invalid
    result = send_email(@contact) if @contact.valid?

    if result == :success
      flash[:success] = t(".#{result}")
      redirect_to :root
    else
      flash[:error] = t(".#{result}")
      render :contact
    end
  end

  private

  # Relative to #contact_send, just send contact email
  # @param [Contact] contact
  # @return [Symbol] return status of the send : `:success` or `:error`
  def send_email(contact)
    result = :flood
    Rails.cache.fetch("contact.flood_control.#{session.id}",
                      expires_in: 1.hour) do
      MainMailer.contact(contact.name, contact.email,
                         contact.message).deliver_later
      result = :success
    end
    result
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
# Handle global helpers
module ApplicationHelper
  include TheaterWeekHelper
end

app/helpers/theater_week_helper.rb
# Manage weeks for theater (from wednesday to tuesday)
module TheaterWeekHelper
  # Get current theater week interval (from next wednesday to next tuesday
  # included)
  def current_theater_week
    to = Date.today.next_week.next_day(2)
    to -= 1.week if Date.today.wday <= 2

    Date.today..to
  end

  # Get next theater week interval (from next wednesday to next tuesday
  # included)
  def next_theater_week
    from = Date.today.next_week.next_day(2)
    from -= 1.week if Date.today.wday <= 2

    from..(from + 1.week)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CineVOlle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="<%= t '.meta_description' %>" />
  <meta property="og:description" content="<%= t '.meta_description' %>" />
  <meta property="og:image" content="" />
</head>
<body>
  <div class="container">
    <div class="header clearfix" id="header">
      <nav>
        <ul class="nav nav-pills pull-right">
          <%- [
            { page: '.header.home' , path: root_path },
            { page: '.header.about', path: about_path },
            { page: '.header.contact', path: contact_path }
          ].each do |link| %>
            <li role="presentation"<% if request.env['PATH_INFO'] == link[:path] %> class="active"<% end %>>
              <%= link_to t(link[:page]), link[:path] %>
            </li>
          <%- end %>
        </ul>
      </nav>
      <h3 class="text-muted">CineVOlle</h3>
    </div>

    <% flash.each do |name, message| -%>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= raw message %>
      </div>
    <% end -%>

    <%= yield %>

  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'auto');
    ga('send', 'pageview');
  </script>

  <!-- Github Ribbon -->
  <a href="https://github.com/Rykian/CineVOlle"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>
</body>
</html>

app/views/shared/_movie.html.erb
<div class="movie">
  <%= image_tag movie.poster.url(:small) %>
  <h2><%= movie.title %></h2>
  <div class="directors"><%= t 'shared.movie.by', directors: movie.directors.to_sentence %></div>
  <div class="actors"><%= t 'shared.movie.actors', actors: movie.actors.try(:to_sentence) %></div>
  <p class="plot"><strong><%= t 'shared.movie.plot' %></strong> <%= movie.plot %></p>
  <div class="sessions"><strong><%= t 'shared.movie.sessions' %></strong>

  <%= movie.sessions_by_date_for(current_theater_week).values.flatten.map { |v| l v, format: :long }.to_sentence %></div>

  <div class="see_on_allocine"><a href="<%= movie.allocine_link %>">Voir sur Allocine</a></div>
</div>

app/views/welcome/about.html.erb
<p><%= raw t '.purpose', author: link_to('Thibault Lacroux', 'http://github.com/Rykian') %></p>

<p><%=t '.goal' %></p>

<p><%= raw t '.available_on_github', github: 'https://github.com/Rykian/CineVOlle' %></p>

app/views/welcome/contact.html.erb
<%= form_for(@contact, url: contact_send_path) do |f| %>
  <div class="form-group">
    <%= f.label :name, t('.name') %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, t('.email') %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :message, t('.message') %>
    <%= f.text_area :message, rows: 10, class: 'form-control' %>
  </div>
  <%= f.submit t('.send'), class: 'btn btn-default' %>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>CineVOlle</h1>
  <p class="lead"><%=t '.description' %></p>

  <%= form_tag '/register', class: 'form-inline xhr-enabled' do %>
    <div class="form-group">
      <input type="email" name="email" class="form-control input-lg" placeholder="Votre email" required="required" />
      <button type="submit" class="btn btn-lg btn-success"><%=t '.signup' %></button>
    </div>
  <% end %>
</div>

<div>
  <ul class="nav nav-tabs">
    <li role="presentation" class="active">
      <a href="#" data-week="current"><%=t '.current' %></a>
    </li>
    <li role="presentation">
      <a href="#" data-week="next"><%=t '.next' %></a>
    </li>
  </ul>

  <% [@current_week, @next_week].each_with_index do |week, i| %>
    <div class="movie-list" id="<%= i== 0 ? 'current' : 'next' %>">
      <% if week.count > 0 %>
        <% week.each do |movie| %>
          <%= render partial: 'shared/movie.html.erb', locals: { movie: movie } %>
        <% end %>
      <% else %>
        <p class="text-center"><%=t '.no_movie.' + (i == 0 ? 'current' : 'next') %></p>
      <% end %>
    </div>
  <% end %>
</div>